config/routes.rb
# frozen_string_literal: true

# Routes of project
Rails.application.routes.draw do
  get 'companies_dashboards/index'

  root 'dashboards#index'

  get 'job_posts/search'

  get 'admins/companies'
  get 'admins/jobseekers'
  get 'admins/job_posts'
  get 'admins/index'
  get 'admins/resumes'
  get 'admins/user_list'
  get 'admins/applied_job/:user_id' => 'admins#applied_job',
      as: :admin_applied_job
  delete 'admins/destroy_jobseeker/:user_id' => 'admins#destroy_jobseeker',
         as: :admin_destroy_jobseeker

  devise_for :companies, controllers: {
    registrations: 'companies/registrations',
    sessions: 'companies/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users do
    resources :job_posts, only: %i[index show] do
      get 'apply_job', on: :member
      get 'apply_job_destroy', on: :member
      member do
        get 'apply_job'
      end
    end
  end
  resources :resumes
  resources :charges
  resources :apply_jobs
  resources :companies do
    resources :reviews do
      collection do
        get 'review_list'
      end
    end
    resources :job_posts do
      member do
        get 'view_candidates'
      end
      collection do
        get 'company_jobs_list'
      end
    end
  end
  if Rails.env.development?
    scope format: true, constraints: { format: /jpg|png|gif|PNG/ } do
      get '/*anything',
          to: proc { [404, {}, ['']] },
          constraints: lambda { |request|
                         !request.path_parameters[:anything]
                                 .start_with?('rails/')
                       }
    end
  end

  # match '*unmatched', to: 'application#route_not_found', via: :all
end

app/views/admins/applied_job.html.erb
<div class="container mt-4">
  <h4>Job Posts</h4>
  <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
  <div class="table-responsive">
    <table class="table table-sm">
      <thead class="thead">
        <tr>
          <th>Profile</th>
          <th>Type</th>
          <th>Salary</th>
          <th>Location</th>
          <th>View</th>
          <th>Edit</th>
          <th>Delete</th>
          <th>Status</th>
        </tr>
      </thead>
      <% @posts.each do |post| %>
      <tbody>
        <tr>
          <td><%= post.job_post.job_title %></td>
          <td><%= post.job_post.job_type %></td>
          <td><%= post.job_post.salary_min %> - <%= post.job_post.salary_max %></td>
          <td><%= post.job_post.location %></td>
          <td>
            <%= link_to company_job_post_path(post.job_post.company, post) do %>
            <%= content_tag :span, "", class: "icon-eye btn btn-outline-primary"%>
            <% end %>
          </td>
          <td>
            <%= link_to edit_company_job_post_path(post.job_post.company, post) do %>
            <% content_tag :span, "", class: "icon-edit btn btn-outline-info" %>
            <% end %>
          </td>
          <td>
            <%= link_to company_job_post_path(post.job_post.company, post) do %>
            <% content_tag :span, "", class: "icon-delete btn btn-outline-danger", method: :delete ,data: {confirm:"Are you sure?"} %>
            <% end %>
          </td>
          <td>
            <%= post.status%>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
</div>

app/views/admins/companies.html.erb
<div class="container mt-4">
  <h4>Companies</h4>
  <%= will_paginate @companies, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
  <div class="table-responsive">
    <table class="table table-sm">
      <thead class="thead">
        <tr>
          <th>Company</th>
          <th>city,state</th>
          <th>View</th>
          <th>Edit</th>
          <th>Delete</th>
          <th>Status</th>
        </tr>
      </thead>
      <% @companies.each do |company| %>
      <tbody>
        <tr>
          <td><%= company.title %></td>
          <td><%= company.city%> <%= company.state%></td>
          <td>
            <%= link_to company_path(company) do %>
            <% content_tag :span, "", class: "icon-eye btn btn-outline-primary" %>
            <% end %>
          </td>
          <td>
            <%= link_to edit_company_path(company) do %>
            <% content_tag :span, "", class: "icon-edit btn btn-outline-info" %>
            <% end %>
          </td>
          <td>
            <%= link_to company_path(company), method: :delete, data: {confirm:"Are you sure?"} do  %>
            <% content_tag :span, "", class: "icon-delete btn btn-outline-danger" %>
            <% end %>
          </td>
          <td><%= company.status %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <%= will_paginate @companies, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
</div>

app/views/admins/index.html.erb
<div class="container mt-3 mb-4">
  <h4><b>Dashboard</b></h4><br>
  <div class="row">
  <div class="col-xl-3 col-sm-6 py-2">
      <div class="card text-white bg-info h-100">
        <div class="card-body bg-info d-flex flex-column justify-content-center align-items-center">
          <h1 class="display-4"><%= User.all.count-1 %></h1>
          <h5 class="text">Users</h5>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 py-2">
      <div class="card text-white bg-danger h-100">
        <div class="card-body bg-danger d-flex flex-column justify-content-center align-items-center">
          <h1 class="display-4"><%= Company.all.count %></h1>
          <h5 class="text">Companies</h5>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 py-2">
      <div class="card text-white bg-warning h-100">
        <div class="card-body bg-warning d-flex flex-column justify-content-center align-items-center">
          <h1 class="display-4"><%= JobPost.all.count %></h1>
          <h5 class="text">Job Posts</h5>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 py-2">
      <div class="card text-white bg-success h-100">
        <div class="card-body bg-success d-flex flex-column justify-content-center align-items-center">
          <h1 class="display-4"><%= ApplyJob.select(:user_id).distinct.count %></h1>
          <h5 class="text">Jobseekers</h5>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div class="row mt-5">
    <div class="col-md-6">
      <center><b>Job Applied per Day</b></center>
      <%= line_chart ApplyJob.group_by_day(:created_at).count %>
    </div>
    <div class="col-md-6">
      <center><b>Job Post Added per Day</b></center>
      <%= line_chart JobPost.group_by_day(:created_at).count %>
    </div>  
  </div>
</div>

app/views/admins/job_posts.html.erb
<div class="container mt-4">
  <h4>Job Posts</h4>
  <%= will_paginate @job_posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
  <div class="table-responsive">
    <table class="table table-sm">
      <thead class="thead">
        <tr>
          <th>Profile</th>
          <th>Type</th>
          <th>Salary</th>
          <th>Location</th>
          <th>View</th>
          <th>Edit</th>
          <th>Delete</th>
          <th>Candidates</th>
          <th>Status</th>
        </tr>
      </thead>
      <% @job_posts.each do |post| %>
      <tbody>
        <tr>
          <td><%= post.job_title %></td>
          <td><%= post.job_type %></td>
          <td><%= post.salary_min %> - <%= post.salary_max %></td>
          <td><%= post.location %></td>
          <td>
            <%= link_to company_job_post_path(post.company, post) do %>
            <%= content_tag :span, "", class: "icon-eye btn btn-outline-primary"%>
            <% end %>
          </td>
          <td>
            <%= link_to edit_company_job_post_path(post.company, post) do %>
            <%= content_tag :span, "", class: "icon-edit btn btn-outline-info"%>
            <% end %>
          </td>
          <td>
            <%= link_to company_job_post_path(post.company, post), method: "delete", data: {confirm:"Are you sure?"} do %>
            <%= content_tag :span, "", class: "icon-delete btn btn-outline-danger"%>
            <% end %>
          </td>
          <td>
            <%= link_to '<span class= "icon-person"></span>'.html_safe, view_candidates_company_job_post_path(post.company, post), class: "btn btn-outline-info"%>
          </td>
          <td>
            <%= form_for(post, url: company_job_post_path(post.company, post)) do |f| %>
            <div class='form-group'>
              <%= f.select :status, JobPost.statuses.keys, {}, { value: post.status, class: 'custom-select', onchange: 'this.form.submit();' } %>
            </div>
            <% end %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <%= will_paginate @job_posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
</div>

app/views/admins/jobseekers.html.erb
<% if !@jobseekers.blank? %>
  <div class="container mt-4">
    <h4>jobseekers</h4>
    <%= will_paginate @jobseekers, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
    <div class="table-responsive">
      <table class="table">
        <thead class="thead">
          <tr>
            <th>Name</th>
            <th>Contact No.</th>
            <th>Gender</th>
            <th>Resume</th>
            <th>Applied in jobs</th>
            <th>Delete</th>
          </tr>
        </thead>
        <% @jobseekers.each do |jobseeker| %>
        <tbody>
          <tr>
            <td><%= jobseeker.user.first_name %> <%= jobseeker.user.last_name %></td>
            <td><%= jobseeker.user.mobile %></td>
            <td><%= jobseeker.user.gender %></td>
            <td><%= link_to 'Resume', url_for(jobseeker.user.resume.resume_file), class: "btn btn-outline-primary" %></td>
            <td><%= link_to 'Applied job', admin_applied_job_path(jobseeker.user.id), class: "btn btn-outline-primary"  %>
            </td>
            <td>
              <%= link_to 'delete',admin_destroy_jobseeker_path(jobseeker.user.id), method: :delete, class: "btn btn-danger"  %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
      <%= will_paginate @jobseekers, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
    </div>
<% else %>
  <div class="mt-4 d-flex justify-content-center">
    <h4>No Jobseekers!!!</h4>
  </div>
<% end %>

app/views/admins/resumes.html.erb
<% if !@resumes.blank? %>
  <div class="container mt-4">
    <h4>Resumes</h4>
    <div class="table-responsive">
      <table class="table table-sm">
        <thead class="thead">
          <tr>
            <th>Field Title</th>
            <th>User name</th>
            <th>Resume File</th>
            <th>Edit</th>
            <th>Remove</th>
          </tr>
        </thead>
        <% @resumes.each do |resume| %>
        <tbody>
          <tr>
            <td><%= resume.file_name %></td>
            <td><%= resume.user.first_name%> <%= resume.user.last_name%></td>
            <td>
              <%= link_to url_for(resume.resume_file) do %>
              <%= content_tag :span, "", class: 'icon-download btn btn-outline-success'%>
              <% end %>
            </td>
            <td>
              <%= link_to edit_resume_path(resume) do %>
              <%= content_tag :span,"",class: 'icon-edit btn btn-outline-info' %>
              <% end %>
            </td>
            <td>
              <%= link_to resume_path(resume), method: :delete, data: {confirm:"Are you sure?"} do %>
              <%= content_tag :span,"",class: 'icon-delete btn btn-outline-danger' %>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
<% else %>
  <div class="mt-4 d-flex justify-content-center">
    <h4>No Resumes!!!</h4>
  </div>
<% end %>

app/views/admins/user_list.html.erb
<% if !@users.blank? %>
<div class="container">
  <h4>Users</h4>
  <div class="table-responsive">
    <table class="table table-sm">
      <thead class="thead">
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Mobile</th>
          <th>Gender</th>
          <th>Status</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user|%>
        <tr>
          <td><%= user.first_name%></td>
          <td><%= user.last_name%></td>
          <td><%= user.email%></td>
          <td><%= user.mobile%></td>
          <td><%= user.gender%></td>
          <td></td>
          <td>
            <%= link_to edit_user_path(user) do %>
            <%= content_tag :span, "", class: "icon-edit btn btn-outline-info"%>
            <% end %>
          </td>
          <td>
            <%= link_to user_path(user), method: :delete , data: {confirm:"Are you sure?"} do %>
            <%= content_tag :span, "", class: "icon-delete btn btn-outline-danger"%>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% else %>
  <div class="mt-4 d-flex justify-content-center">
    <h4>No Users!!!</h4>
  </div>
<% end %>