config/routes.rb
# frozen_string_literal: true

# Routes of project
Rails.application.routes.draw do
  get 'companies_dashboards/index'

  root 'dashboards#index'

  get 'job_posts/search'

  get 'admins/companies'
  get 'admins/jobseekers'
  get 'admins/job_posts'
  get 'admins/index'
  get 'admins/resumes'
  get 'admins/user_list'
  get 'admins/applied_job/:user_id' => 'admins#applied_job',
      as: :admin_applied_job
  delete 'admins/destroy_jobseeker/:user_id' => 'admins#destroy_jobseeker',
         as: :admin_destroy_jobseeker

  devise_for :companies, controllers: {
    registrations: 'companies/registrations',
    sessions: 'companies/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users do
    resources :job_posts, only: %i[index show] do
      get 'apply_job', on: :member
      get 'apply_job_destroy', on: :member
      member do
        get 'apply_job'
      end
    end
  end
  resources :resumes
  resources :charges
  resources :apply_jobs
  resources :companies do
    resources :reviews do
      collection do
        get 'review_list'
      end
    end
    resources :job_posts do
      member do
        get 'view_candidates'
      end
      collection do
        get 'company_jobs_list'
      end
    end
  end
  if Rails.env.development?
    scope format: true, constraints: { format: /jpg|png|gif|PNG/ } do
      get '/*anything',
          to: proc { [404, {}, ['']] },
          constraints: lambda { |request|
                         !request.path_parameters[:anything]
                                 .start_with?('rails/')
                       }
    end
  end

  # match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/company.rb
# frozen_string_literal: true

# company model
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :social_links, inverse_of: :company
  accepts_nested_attributes_for :social_links,
                                reject_if: :all_blank, allow_destroy: true
  has_rich_text :about
  has_one_attached :logo
  has_many :reviews, dependent: :destroy
  has_many :job_posts, dependent: :destroy

  enum status: %i[inactive active]

  validates :title, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :pincode, presence: true
  # validates :email, format: { with: /[^@]+@[^\.]+\..+/,
  #                             message: 'Enter valid email address' }
  # validates :password, length: { in: 6..20,
  #                                message: 'Password length (between 6-20)' }
  validates :contact_no, presence: { message: 'Enter valid Mobile' },
                         numericality: true,
                         length: { minimum: 10, maximum: 15 }

  def thumbnail
    logo.variant(resize: '150x150')
  end
end

app/controllers/companies/confirmations_controller.rb
# frozen_string_literal: true

class Companies::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/companies/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Companies::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/companies/passwords_controller.rb
# frozen_string_literal: true

class Companies::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/companies/registrations_controller.rb
# frozen_string_literal: true

# Company controller
class Companies::RegistrationsController < Devise::RegistrationsController
  include Accessible
  skip_before_action :check_user, except: %i[new create]
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def after_sign_up_path_for(_companies)
    companies_dashboards_index_path
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    puts "params ===> #{params}"
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
      params.delete(:current_password)
      resource.update_without_password(params)
    else
      super
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[title about address city state
                                               country pincode contact_no
                                               website status password logo
                                               password_confirmation
                                               facebook instagram linkedin])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[title about address city state
                                               country pincode contact_no
                                               website status password logo
                                               password_confirmation
                                               facebook instagram linkedin])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies/sessions_controller.rb
# frozen_string_literal: true

# Company controller
class Companies::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  include Accessible
  skip_before_action :check_user, only: :destroy

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(_resource)
    companies_dashboard_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/companies/unlocks_controller.rb
# frozen_string_literal: true

class Companies::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

# companies controller
class CompaniesController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource only: %i[show]
  before_action :find_company, only: %i[edit update destroy]

  def index
    @companies = Company.all
    @pages = @companies.paginate(page: params[:page])
  end

  def show
    @company = Company.find(params[:id])
    @reviews = Review.where(company_id: @company.id).order('created_at DESC')

    @avg_review = if @reviews.blank?
                    0
                  else
                    @reviews.average(:rating).round(2)
                  end
  end

  def edit; end

  def update
    if @company.update(company_params)
      redirect_to admins_companies_path,
                  notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @company.destroy
    redirect_to admins_companies_path,
                notice: 'Company was successfully destroyed.'
  end

  private

  def find_company
    @company = Company.find_by(id: params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def company_params
    params.require(:company).permit(:title, :about, :address,
                                    :city, :state, :country,
                                    :pincode, :contact_no, :website,
                                    :status, :logo, :facebook,
                                    :instagram, :linkedin)
  end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

# Company helper
module CompaniesHelper
end

app/views/companies/_company_show_navbar.html.erb
<head>
	<title>Bootstrap Example</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style>
		body {
			top-padding: 40px;
			margin-bottom: 30px;
		}
    
		ul {
			list-style-type: none;
			margin: 0;
			padding: 0;
			color: #000;
			overflow: hidden;
			position: -webkit-sticky;
			/* Safari */
			position: sticky;
			top: 50px;
			z-index: 5;
		}

		li {
			list-style-type: none;
			float: left;
		}

		li a {
			display: block;
			color: #000;
			position: relative;
			text-align: center;
			padding: 14px 16px;
			text-decoration: none;
		}

		.offset:before {
			display: block;
			content: " ";
			height: 150px;
			/* Give height of your fixed element */
			margin-top: -150px;
			/* Give negative margin of your fixed element */
			visibility: hidden;
		}

		.active1 {
			background-color: #007bff;
		}
	</style>
</head>
<ul style='background: #fff' class="mb-4">
	<li class="nav-item <%if current_page?(company_path(@company))%>active1<%end%>"><%= link_to 'About', company_path(@company) %></li>
	<li class="nav-item <%if current_page?(review_list_company_reviews_path(@company))%>active1<%end%>"><%= link_to 'Review', review_list_company_reviews_path(@company)%></li>
	<li class="nav-item <%if current_page?(company_jobs_list_company_job_posts_path(@company))%>active1<%end%>"><%= link_to 'Jobs', company_jobs_list_company_job_posts_path(@company)%></li>
</ul>

app/views/companies/edit.html.erb
<% if current_user %>
<% if current_user.has_role? :admin %>
<div class="container mt-5" style="width:900px;">
  <center>
    <h3>Edit Company Profile</h3>
  </center>

  <%= form_with(model: @company) do |f| %>
  <div class="form-group row">
    <%= f.label :Company_logo, class: "col-form-label col-sm-2"%>
    <div class="col-sm-10">
      <%= f.file_field :logo, class: "form-control"%>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :Name, class: "col-form-label col-sm-2"%>
    <div class="col-sm-10">
      <%= f.text_field :title, autofocus: true, autocomplete: "title", class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :About, class: "col-form-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.rich_text_area :about %>
    </div>
  </div>

  <h3>Address Information</h3>

  <div class="form-group row">
    <%= f.label :Address, class: "col-form-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :address, autofocus: true, autocomplete: "address", class: 'form-control' %>
    </div>

  </div>
  <div class="form-group row">
    <%= f.label :City, class: "col-form-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :city, autofocus: true, autocomplete: "city", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :State, class: "col-form-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :state, autofocus: true, autocomplete: "state", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :County, class: "col-form-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :country, autofocus: true, autocomplete: "country", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :Pincode, class: "col-form-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :pincode, autofocus: true, autocomplete: "pincode", class: 'form-control' %>
    </div>
  </div>

  <!--End of address----------------->

  <!--Contact Information------------>
  <h3>Contact Information</h3>

  <div class="form-group row">
    <div class="col-form-label col-sm-2">
      <span class="icon-facebook"></span>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :facebook, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-form-label col-sm-2">
      <span class="icon-instagram"></span>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :instagram, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-form-label col-sm-2">
      <span class="icon-linkedin"></span>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :linkedin, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-form-label col-sm-2">
      <span class="icon-phone"></span>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :contact_no, autofocus: true, autocomplete: "contact_no", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">

    <div class="col-form-label col-sm-2">
      website
      <span class="icon-link2"></span>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :website, autofocus: true, autocomplete: "website", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status %>
    <%= f.select(:status, Company.statuses.keys, {prompt: 'Select Field'}, class: 'form-control' )%>
  </div>
  <div class="form-group">
    <%= f.submit "Update", class: 'btn btn-group' %>
  </div>
  <% end %>
</div>
<% end %>
<% end %>

app/views/companies/index.html.erb
<div class= "container">
  <section class="ftco-section bg-light">
    <div class="container">
      <div class="row justify-content-center pb-3">
        <div class="col-md-7 heading-section text-center ftco-animate">
          <h2 class="mb-4">Companies</h2>
        </div>
      </div>
      <%= will_paginate @pages, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
        <% @companies.each do |company| %>
        <div class="row">
          <div class="col-md-12 ftco-animate">
            <div class="job-post-item bg-white p-4 d-block d-md-flex align-items-center">
              <div class="mb-1 mb-md-0 mr-3">
                <div class="job-post-item-header d-flex align-items-center">
                  <div class="user-img mr-2"><%= image_tag(company.thumbnail) if company.logo.attached?%></div>
                    <h2 class="mr-3 text-black h3"></span><%= company.title %></h2>
                    <div><span class="icon-my_location"></span> <span><%= company.city%>, <%= company.state%></span></div>      
                  </div>
                </div>
                <div class="ml-auto d-flex">
                  <%= link_to 'View', company_path(company), class: 'btn btn-primary'%>
                </div>
              </div>
            </div>
        </div>
      <% end %>
      <%= will_paginate @pages, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
    </div>
  </section>
</div>

app/views/companies/show.html.erb
<%= render 'companies/company_show_navbar' %>
<div class="container">
	<body>
		<div id="intro" class="offset">
			<div class="jumbotron">
				<div class="container ">
					<div class="row">
						<div class="col-md-2">
							<div class="user-img mr-2"><%= image_tag(@company.thumbnail)if @company.logo.attached?%></div>
						</div>
						<div class="col-md-10">
							<h1><%= @company.title %></h1>
							<div class="star-rating" data-score=<%= @avg_review %>></div>
							<em><%= "#{@reviews.length} reviews" %></em>
						</div>
					</div>
				</div>
			</div>
			<div class="jumbotron">
				<div class="container">
					<h3 class="heading-2">About <%= @company.title%></h3>
					<p><%= @company.about %></p>
				</div>
			</div>
		</div>
		<div id="contact_us" class="offset">
			<div class="jumbotron">
				<div class="container text-center">
					<h3>Contact us</h3>
					<div id="address">
						<ul class="ftco-footer-social list-unstyled d-flex justify-content-center mt-3">
							<li><%= link_to '<span class= "icon-linkedin"></span>'.html_safe,"#{@company.linkedin}"%></li>
							<li><%= link_to '<span class= "icon-facebook"></span>'.html_safe,"#{@company.facebook}"%></li>
							<li><%= link_to '<span class= "icon-instagram"></span>'.html_safe,"#{@company.instagram}"%></li>
						</ul>
					</div>
					<p><span class='icon-phone mr-3'> <%= @company.contact_no%></span></p>
					<p><%= @company.website%></p>
					<p><%= @company.address%></p>
					<p><%= @company.city%> <%= @company.state%></p>
					<p><%= @company.country%> <%= @company.pincode%></p>
				</div>
			</div>
		</div>
</div>
</body>
<div>