config/routes.rb
# frozen_string_literal: true

# Routes of project
Rails.application.routes.draw do
  get 'companies_dashboards/index'

  root 'dashboards#index'

  get 'job_posts/search'

  get 'admins/companies'
  get 'admins/jobseekers'
  get 'admins/job_posts'
  get 'admins/index'
  get 'admins/resumes'
  get 'admins/user_list'
  get 'admins/applied_job/:user_id' => 'admins#applied_job',
      as: :admin_applied_job
  delete 'admins/destroy_jobseeker/:user_id' => 'admins#destroy_jobseeker',
         as: :admin_destroy_jobseeker

  devise_for :companies, controllers: {
    registrations: 'companies/registrations',
    sessions: 'companies/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users do
    resources :job_posts, only: %i[index show] do
      get 'apply_job', on: :member
      get 'apply_job_destroy', on: :member
      member do
        get 'apply_job'
      end
    end
  end
  resources :resumes
  resources :charges
  resources :apply_jobs
  resources :companies do
    resources :reviews do
      collection do
        get 'review_list'
      end
    end
    resources :job_posts do
      member do
        get 'view_candidates'
      end
      collection do
        get 'company_jobs_list'
      end
    end
  end
  if Rails.env.development?
    scope format: true, constraints: { format: /jpg|png|gif|PNG/ } do
      get '/*anything',
          to: proc { [404, {}, ['']] },
          constraints: lambda { |request|
                         !request.path_parameters[:anything]
                                 .start_with?('rails/')
                       }
    end
  end

  # match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/job_post.rb
# frozen_string_literal: true

# Job post model
class JobPost < ApplicationRecord
  has_rich_text :description
  has_rich_text :required_skill
  has_rich_text :extra_skill
  has_rich_text :language

  belongs_to :company
  has_many :comments
  has_many :apply_job, dependent: :destroy
  has_many :users, through: :apply_job

  validates :job_title, presence: true
  validates :description, presence: true
  validates :job_type, presence: true
  validates :salary_min, numericality: { greater_than: 0,
                                         less_than: :salary_max }
  validates :salary_max, numericality: { greater_than_or_equal_to: :salary_min,
                                         greater_than: 0 }

  JOB_TYPE = %w[Part-time Full-time Infulencer].freeze
  enum status: %i[inactive active]
end

app/controllers/job_posts_controller.rb
# frozen_string_literal: true

# Job Post controller
class JobPostsController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource only: %i[company_jobs_list view_candidates search
                                   active_job_list apply_job apply_job_list
                                   show]
  before_action :find_post, only: %i[edit update destroy show view_candidates]
  before_action :find_company, only: %i[new edit create user_job_post]

  def index
    @job_posts = current_company.job_posts.paginate(page: params[:page],
                                                    per_page: 10)
  end

  def new
    @job_post = JobPost.new
  end

  def create
    @job_post = JobPost.new(job_post_params)
    if @job_post.save!
      redirect_to company_job_posts_path, notice: 'Job added'
    else
      flash[:alert] = 'Not added'
      render :new
    end
  end

  def show
    return unless current_user

    session[:return_to] = request.fullpath
    @applied = ApplyJob.where('user_id=? AND job_post_id=?',
                              current_user.id, @job_post.id)
  end

  def edit; end

  def update
    if @job_post.update(job_post_params)
      if current_company
        redirect_to company_job_posts_path,
                    notice: 'Job Post was successfully updated.'
      elsif current_user
        redirect_to admins_job_posts_path
      end
    else
      render :edit
    end
  end

  def destroy
    @job_post.destroy
    if current_company
      redirect_to company_job_posts_path,
                  notice: 'Job Post was successfully destroyed.'
    elsif current_user
      redirect_to admins_job_posts_path
    end
  end

  def company_jobs_list
    @company = Company.find(params[:company_id])
    @job_list = @company.job_posts.paginate(page: params[:page], per_page: 10)
  end

  def view_candidates
    @candidates = ApplyJob.eager_load(:user, :job_post)
                          .where('job_posts.id = ? ', params[:id])
    @pages = @candidates.paginate(page: params[:page])
  end

  def apply_job_list
    @apply_job_list = ApplyJob.all
  end

  def apply_job
    if current_user.resume
      @apply_job = ApplyJob.new(user_id: current_user.id,
                                job_post_id: params[:id], apply: true)
      if @apply_job.save!
        redirect_to user_job_post_path, notice: 'Job Appllied successfully'
      else
        render 'new'
      end
    else redirect_to new_user_resume_path(current_user)
    end
  end

  def active_job_list
    @job_posts = JobPost.all
  end

  def search
    if params[:job_title] == ''
      @job_posts = if params[:location] == ''
                     JobPost.all
                   else
                     JobPost.where(location: params[:location])
                   end
    else
      if params[:location] == ''
        @job_posts = JobPost.where(job_title: params[:job_title])
      else
        @job_posts = JobPost.where(job_title: params[:job_title], location: params[:location])
      end
    end
  end

  private

  def find_post
    @job_post = JobPost.find(params[:id])
  end

  def find_company
    @company = Company.find(params[:company_id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def job_post_params
    params.require(:job_post).permit(:job_title, :description, :job_type,
                                     :location, :required_skill, :extra_skill,
                                     :salary_max, :last_apply_date, :language,
                                     :job_field, :vacancy, :status,
                                     :company_id, :salary_min)
  end
end

app/views/job_posts/_active_job_post.html.erb
<%= link_to change_job_post_status_company_job_post_path(job_post.company_id, job_post),remote: true do %>
  <input type = 'checkbox' checked>
  <span class="slider round"></span>
<% end %>

app/views/job_posts/_change_applyjob_status.js.erb
<%= link_to change_job_post_status_company_job_post_path(apply_job),remote: true do %>
  <input type = 'checkbox' checked>
  <span class="slider round"></span>
<% end %>

app/views/job_posts/_form.html.erb
<%= form_with(model:[@company, @job_post], validate: true) do |form| %>

  <div class="field">
    <%= form.hidden_field :company_id, value: @company.id %>
  </div>

  <div class="form-group">
    <%= form.label :Post_name %>
    <%= form.text_field :job_title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :Description %>
    <%= form.rich_text_area :description %>
  </div>

  <div class="form-group">
    <%= form.label :Job_Type %>
    <%= form.select :job_type, JobPost::JOB_TYPE,{}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Location %>
    <%#= form.text_field :location, class: "form-control" %>
    <%= form.select :location, options_from_collection_for_select(JobPost.select(:location).distinct, :location, :location), {:class=>'form-control'} %>
  </div>

  <div class="form-group">
    <%= form.label :Required_Skills %>
    <%= form.rich_text_area :required_skill %>
  </div>

  <div class="form-group">
    <%= form.label :Extra_Skills %>
    <%= form.rich_text_area :extra_skill, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Minimum_Salary %>
    <%= form.text_field :salary_min, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Maximum_Salary %>
    <%= form.text_field :salary_max, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Last_Apply_Date %>
    <%= form.text_field :last_apply_date,  class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Language %>
    <%= form.rich_text_area :language, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Job_Field %>
    <%= form.text_field :job_field, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Vacancy %>
    <%= form.number_field :vacancy, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :Status %>
    <%= form.select(:status, JobPost.statuses.keys, {prompt: 'Select Field'}, class: 'form-control' )%>
  </div>

  <center>
    <div class="form-group">
      <%= form.submit :Submit, class: "btn btn-primary" %>
    </div>
  </center>
<% end %>

app/views/job_posts/_job_posts_list.html.erb
<section class="ftco-section bg-light">
  <div class="container">
    <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section text-center ftco-animate">
        <h2 class="mb-4"><span>Recent</span> Jobs</h2>
      </div>
    </div>
    <div class="row">
      <% if !@job_posts.blank? %>
        <% @job_posts.each do |job| %>
          <div class="col-md-12 ftco-animate">
            <div class="job-post-item bg-white p-4 d-block d-md-flex align-items-center">
              <div class="mb-4 mb-md-0 mr-5">
                <div class="job-post-item-header d-flex align-items-center">
                  <h2 class="mr-3 text-black h3"><%= job.job_title %></h2>
                  <div class="badge-wrap">
                    <span class="bg-primary text-white badge py-2 px-3"><%= job.job_type %></span>
                  </div>
                </div>
                <div class="job-post-item-body d-block d-md-flex">
                  <div class="mr-3"><span class="icon-layers"></span>
                    <%= link_to "#{job.company.title}", company_path(job.company_id)%></div>
                  <div><span class="icon-my_location"></span> <span><%= job.location %></span></div>
                </div>
              </div>
              <% if user_signed_in? %>
                <div class="ml-auto d-flex">
                  <%= link_to "Show more", user_job_post_path(current_user, job), class:"btn btn-primary py-2 mr-1" %>
                </div>
              <% else %>
                <div class="ml-auto d-flex">
                  <%= link_to "Show more",company_job_post_path(job.company_id, job), class:"btn btn-primary py-2 mr-1" %>
                </div>
              <% end %>
            </div>
          </div><!-- end -->
        <% end %>
      <% else %>
        <span>Jobs not available</span>
      <% end %>
    </div>
  </div>
</section>

app/views/job_posts/change_job_post.js.erb
<% if @job_post.status %>
  $('#status-<%= @job_post.id %>').html("<%= escape_javascript(render partial: 'active_job_post', locals: {job_post: @job_post} ) %>");
<%else%>
  $('#status-<%= @job_post.id %>').html("<%= escape_javascript(render partial: 'inactive_job_post', locals: {job_post: @job_post} ) %>");
<%end%>

app/views/job_posts/company_jobs_list.html.erb
<%= render 'companies/company_show_navbar'%>
<div class="container">
  <%= will_paginate @job_list, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center mt-3 mb-5) %>
  <div class="row">
    <% if !@job_list.blank? %>
      <% @job_list.each do |job| %>
        <div class="col-md-12 ftco-animate">
          <div class="job-post-item bg-white p-4 d-block d-md-flex align-items-center">
            <div class="mb-4 mb-md-0 mr-5">
              <div class="job-post-item-header d-flex align-items-center">
                <h2 class="mr-3 text-black h3"><%= job.job_title %></h2>
                <div class="badge-wrap">
                  <span class="bg-primary text-white badge py-2 px-3"><%= job.job_type %></span>
                </div>
              </div>
              <div class="job-post-item-body d-block d-md-flex">
                <div class="mr-3"><span class="icon-layers"></span>
                  <%= link_to "#{job.company.title}", company_path(job.company_id)%></div>
                <div><span class="icon-my_location"></span> <span><%= job.location %></span></div>
              </div>
            </div>
            <% if user_signed_in? %>
              <div class="ml-auto d-flex">
                <%= link_to "Show more", user_job_post_path(current_user, job), class:"btn btn-primary py-2 mr-1" %>
              </div>
              <% else %>
              <div class="ml-auto d-flex">
                <%= link_to "Show more",company_job_post_path(job.company_id, job), class:"btn btn-primary py-2 mr-1" %>
              </div>
              <% end %>
          </div>
        </div><!-- end -->
      <% end %>`
    <% else %>
      <span>Jobs not available</span>
    <% end %>
  </div>
  <%= will_paginate @job_list, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center mb-5 mt-4) %>
</div>

app/views/job_posts/edit.html.erb
<div class="container" style="width:900px;">
  <h2>Your Posts</h2>
  <div class="ftco-section bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8 mb-5">
          <%= render 'form', job_post: @job_post %>
        </div>
        <div class="col-lg-4">
          <div class="p-4 mb-3 bg-white">
            <h3 class="h5 text-black mb-3">Company Info</h3>
            <p class="mt-3">
            <h3><%= @company.title %></h3>
            <p>
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4"><%= @company.address %> <%= @company.city %></p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><%= @company.contact_no %></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-4"><%= @company.email %></p>

              <p class="mb-0 font-weight-bold">Website</p>
              <p class="mb-0"><%= @company.website %></p>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/job_posts/index.html.erb
<div class="container d-flex justify-content-center mt-2 mb-4">
  <br>
  <%= link_to 'Add New Post', new_company_job_post_path(current_company)	, class: "btn btn-success" %>
</div>
<div class="container">
  <%= will_paginate @job_posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
  <div class="table-responsive">
    <table class='table table-sm'>
      <thead class="thead">
        <tr>
          <th>Post Name</th>
          <th>Location</th>
          <th>Vacancy</th>
          <th>View Candidates</th>
          <th>Show</th>
          <th>Edit</th>
          <th>Delete</th>
          <th>Status</th>
        </tr>
      </thead>
      <% @job_posts.each do |job_post| %>
      <tbody>
        <tr>
          <td><%= job_post.job_title %></td>
          <td><%= job_post.location %></td>
          <td><%= job_post.vacancy %></td>
          <td>
            <%= link_to view_candidates_company_job_post_path(current_company.id,job_post) do %>
            <%= content_tag :span,"candidates",class: "icon-person btn btn-outline-info"%>
            <% end %>
          </td>
          <td>
            <%= link_to company_job_post_path(current_company.id,job_post) do %>
            <%= content_tag :span,"", class: "icon-eye btn btn-outline-primary" %>
            <% end %>
          </td>
          <td>
            <%= link_to edit_company_job_post_path(current_company.id,job_post) do %>
            <%= content_tag :span,"", class: "icon-edit btn btn-outline-info" %>
            <% end %>
          </td>
          <td>
            <%= link_to company_job_post_path(current_company.id,job_post), method: :delete, data: {confirm:"Are you sure?"} do %>
            <%= content_tag :span,"", class: "icon-delete btn btn-outline-danger" %>
            <% end %>
          </td>
          <td>
            <%= form_for(job_post, url: company_job_post_path(job_post.company_id, job_post)) do |f| %>
            <div class='form-group'>
              <%= f.select :status, JobPost.statuses.keys, {}, { value: job_post.status, class: 'custom-select', onchange: 'this.form.submit();' } %>
            </div>
            <% end %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <%= will_paginate @job_posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
</div>

app/views/job_posts/new.html.erb
<div class="container">
  <div class="ftco-section bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8 mb-5">
          <h2> Post a Job </h2>
          <%= render 'form', job_post: @job_post %>
        </div>
        <div class="col-lg-4">
          <div class="p-4 mb-3 bg-white">
            <h3 class="h5 text-black mb-3">Company Info</h3>
            <p class="mt-3">
            <h3><%= current_company.title %></h3>
            <p>
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4"><%= current_company.address %> <%= current_company.city %></p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><%= current_company.contact_no %></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-4"><%= current_company.email %></p>

              <p class="mb-0 font-weight-bold">Website</p>
              <p class="mb-0"><%= current_company.website %></p>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/job_posts/search.html.erb
<div class="container mt-5">
  <div class="row">
    <% if !@job_posts.blank? %>
    <% @job_posts.each do |job| %>
    <div class="col-md-12 ftco-animate">
      <div class="job-post-item bg-white p-4 d-block d-md-flex align-items-center">
        <div class="mb-4 mb-md-0 mr-5">
          <div class="job-post-item-header d-flex align-items-center">
            <h2 class="mr-3 text-black h3"><%= job.job_title %></h2>
            <div class="badge-wrap">
              <span class="bg-primary text-white badge py-2 px-3"><%= job.job_type %></span>
            </div>
          </div>
          <div class="job-post-item-body d-block d-md-flex">
            <div class="mr-3"><span
                class="icon-layers"></span><%= link_to "#{job.company.title}", company_path(job.company_id)%></div>
            <div><span class="icon-my_location"></span> <span><%= job.location %></span></div>
          </div>
        </div>
        <div class="ml-auto d-flex">
          <%= link_to "Show more", company_job_post_path(job.company.id,job), class:"btn btn-primary py-2 mr-1" %>
        </div>
      </div>
    </div><!-- end -->
    <% end %>
    <% else %>
    <span>Jobs not available</span>
    <% end %>
  </div>
</div>

app/views/job_posts/show.html.erb
<% if current_user %>
<% if @applied.any? %>
<center>
  <div class="mt-4">
    <h3>Your application applied.</h3>
  </div>
</center>
<% end %>
<% end %>

<center>
  <div class="mt-4">
    <h1>Job Details</h1>
  </div>
</center>

<div class="container">
  <div class="ftco-section bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8 mb-5">
          <p>
            <h3><%= @job_post.job_title %></h3>
            </h4><%= @job_post.job_type %></h4>
            <spam class="icon-location_city"></spam><%= @job_post.location %></b>
          </p>
          <div class="card">
            <div class="card-header">
              <b>Profile Details</b>
            </div>
            <div class="card-body">
              <p><%= @job_post.description %></p>
            </div>
          </div>
          <div class="container">
            <p><b>Salary : </b><%= @job_post.salary_min %> - <%= @job_post.salary_max %></p>
            <% if !@job_post.language.blank? %>
            <p><b>Preferred Language : </b><%= @job_post.language %></p>
            <% end %>
            <% if !@job_post.required_skill.blank? %>
            <p><b>Required Skills </b><%= @job_post.required_skill %></p>
            <% end %>
            <% if !@job_post.extra_skill.blank? %>
            <p><b>Extra Skills </b><%= @job_post.extra_skill %></p>
            <% end %>
            <% if !@job_post.last_apply_date&.strftime("%d %b, %Y").blank? %>
            <p><b>Last date to apply is <%= @job_post.last_apply_date&.strftime("%d %b, %Y") %><p>
                  <% end %>
          </div>
          <% if current_user %>
          <% if !@applied.any? %>
          <% if current_user.has_role? :job_seeker %>
          <center>
            <%= link_to 'Apply Job', apply_job_user_job_post_path(current_user, @job_post), class: "btn btn-primary" %>
          </center>
          <% end %>
          <% end %>
          <% else %>
          <center>
            <%= link_to 'Apply Job', new_user_session_path, class: "btn btn-primary" %>
          </center>
          <%end%>
        </div>
        <div class="p-4 mb-3 bg-white">
          <div class="card">
            <div class="card-header">
              <b>Company Details</b>
            </div>
            <div class="card-body">
              <div class="container text-center">
                <p class="font-weight-bold"><%= @job_post.company.title%></p>
                <p><%= @job_post.company.website%></p>
                <p><%= @job_post.company.address%></p>
                <p><%= @job_post.company.city%> <%= @job_post.company.state%></p>
                <p><%= @job_post.company.country%> <%= @job_post.company.pincode%></p>
                <ul class="ftco-footer-social list-unstyled d-flex justify-content-center mt-3">
                  <li><%= link_to '<span class= "icon-linkedin"></span>'.html_safe,"#{@job_post.company.linkedin}"%>
                  </li>
                  <li><%= link_to '<span class= "icon-facebook"></span>'.html_safe,"#{@job_post.company.facebook}"%>
                  </li>
                  <li><%= link_to '<span class= "icon-instagram"></span>'.html_safe,"#{@job_post.company.instagram}"%>
                  </li>
                </ul>
                <p><span class='icon-phone mr-3'> <%= @job_post.company.contact_no%></span></p>

                <%= link_to "Show more ", company_path(@job_post.company_id), class: 'btn btn-primary'%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/job_posts/view_candidates.html.erb
<div class="container">
  <h4>Candidates</h4>
  <%= will_paginate @pages, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
  <% if !@candidates.blank? %>
  <div class="table-responsive">
    <table class="table table-sm">
      <thead class="thead">
        <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Contact No.</th>
          <th>Resume</th>
          <th>Status</th>
        </tr>
      </thead>
      <% @candidates.each do |candidate| %>
      <tbody>
        <tr>
          <td><%= candidate.user.first_name %> <%= candidate.user.last_name %></td>
          <td><%= candidate.user.email %></td>
          <td><%= candidate.user.mobile %></td>
          <td><%= link_to 'Resume', url_for(candidate.user.resume.resume_file) %></td>
          <td>
            <%= form_with(url: apply_job_path(candidate), method: :patch) do |f| %>
            <div class='form-group'>
              <%= f.select :status, ApplyJob::STATUS,{ :selected =>  candidate[:status]}, class: 'custom-select', onchange: 'this.form.submit();' %>
            </div>
            <% end %>
          </td>
        </tr>
      </tbody>
      <% end %>
      <br>
      <%= will_paginate @pages, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
      <% else %>
      <h1>Data not found</h1>
    </table>
    <% end %>
  </div>
</div>