config/routes.rb
# frozen_string_literal: true

# Routes of project
Rails.application.routes.draw do
  get 'companies_dashboards/index'

  root 'dashboards#index'

  get 'job_posts/search'

  get 'admins/companies'
  get 'admins/jobseekers'
  get 'admins/job_posts'
  get 'admins/index'
  get 'admins/resumes'
  get 'admins/user_list'
  get 'admins/applied_job/:user_id' => 'admins#applied_job',
      as: :admin_applied_job
  delete 'admins/destroy_jobseeker/:user_id' => 'admins#destroy_jobseeker',
         as: :admin_destroy_jobseeker

  devise_for :companies, controllers: {
    registrations: 'companies/registrations',
    sessions: 'companies/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users do
    resources :job_posts, only: %i[index show] do
      get 'apply_job', on: :member
      get 'apply_job_destroy', on: :member
      member do
        get 'apply_job'
      end
    end
  end
  resources :resumes
  resources :charges
  resources :apply_jobs
  resources :companies do
    resources :reviews do
      collection do
        get 'review_list'
      end
    end
    resources :job_posts do
      member do
        get 'view_candidates'
      end
      collection do
        get 'company_jobs_list'
      end
    end
  end
  if Rails.env.development?
    scope format: true, constraints: { format: /jpg|png|gif|PNG/ } do
      get '/*anything',
          to: proc { [404, {}, ['']] },
          constraints: lambda { |request|
                         !request.path_parameters[:anything]
                                 .start_with?('rails/')
                       }
    end
  end

  # match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/resume.rb
# frozen_string_literal: true

# Resume Model
class Resume < ApplicationRecord
  belongs_to :user
  has_one_attached :resume_file
end

app/controllers/resumes_controller.rb
# frozen_string_literal: true

# Resume for user controller
class ResumesController < ApplicationController
  load_and_authorize_resource
  before_action :find_resume, only: %i[edit update destroy show]

  def index
    @resumes = current_user.resume
  end

  def new
    @resume = Resume.new
  end

  def create
    @user = Resume.find_by(user_id: current_user)
    return unless @user.nil?

    @resume = Resume.new(resume_params)
    @resume.user_id = current_user.id
    if @resume.save
      redirect_to session[:return_to], notice: 'Resume Uploaded.'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @resume.update(resume_params)
      redirect_to resumes_path, notice: 'Resume updated.'
    else
      render :edit
    end
  end

  def destroy
    @resume.destroy
    @apply_job = ApplyJob.where(user_id: @user)
    @apply_job.delete_all
    redirect_to resumes_path, notice: 'Resume destroyed.'
  end

  def resume_list
    @resumes = Resume.all
  end

  private

  def find_resume
    @resume = Resume.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def resume_params
    params.require(:resume).permit(:file_name, :resume_file)
  end
end

app/helpers/resumes_helper.rb
# frozen_string_literal: true

# Resume Helper
module ResumesHelper
end

app/views/resumes/_resume.html.erb
<div class="container mt-4">
  <%= form_with(model: resume, local: true) do |f| %>
    <% if resume.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(resume.errors.count, "error") %> prohibited this demodb from being saved:</h2>
        <ul>
          <% resume.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :file_name, 'Field Name' %>
      <%= f.text_field :file_name, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :resume_file %>
      <%= f.file_field :resume_file, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit :Submit, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/resumes/_resume_list.html.erb
<div class="container">
  <% @resumes.each do |resume| %>
    <table class="table">
      <tr>
        <td><%= resume.file_name %></td>
        <td><%= link_to 'download', url_for(resume.resume_file) %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/resumes/edit.html.erb
<div class="mt-4">
  <h2><b><center>Edit Resume</center></b></h2>
</div>
<%= render 'resume', resume: @resume %>

app/views/resumes/index.html.erb
<div class="container">
  <% if !@resumes.present?%>
    <center>
      <div class="mt-3">
        <%= link_to "Upload Resume ", new_user_resume_path, class: "btn btn-success btn-lg" %>
      </div>
    </center>
  <% else %>
  <br>
  <h3>Your Resume</h3>
  <div class="table-responsive">
    <table class="table table-sm">
      <thead class="thead">
        <tr>
          <th>Field Title</th>
          <th>User name</th>
          <th>Resume File</th>
          <th>Edit</th>
          <th>Remove</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @resumes.file_name %></td>
          <td><%= @resumes.user.first_name%> <%= @resumes.user.last_name%></td>
          <td>
            <%= link_to url_for(@resumes.resume_file) do %>
            <%= content_tag :span, "", class: 'icon-download btn btn-outline-success'%>
            <% end %>
          </td>
          <td>
            <%= link_to edit_resume_path(current_user.id, @resumes) do %>
            <%= content_tag :span,"",class: 'icon-edit btn btn-outline-info' %>
            <% end %>
          </td>
          <td>
            <%= link_to resume_path( current_user.id, @resumes), method: :delete, data: {confirm:"Are you sure?"} do %>
            <%= content_tag :span,"",class: 'icon-delete btn btn-outline-danger' %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

app/views/resumes/new.html.erb
<div class="mt-4">
  <h2><b><center>Upload Resume</center></b></h2>
</div>
<%= render 'resume', resume: @resume %>

app/views/resumes/show.html.erb
<h1>Resumes#show</h1>
<p>Find me in app/views/resumes/show.html.erb</p>